### PR TITLE
bump version to 2.17

### LINKED ISSUE #233: [BUG]Bump plugin version in 2.x branch to 2.17
**What is the bug?**

- Bump plugin version in 2.x branch to 2.17. (As this plugin is expected to release with opensearch 2.17)

### PR DESCRIPTION
**Pull request by saimedhi**
### Description

- Bump version to 2.17.0.0
- Renamed plugin in package.json , opensearch_dashboards.json

### Issues Resolved
closes #233

### Check List

- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
Why do we need to do version bump manually? Once onboarded to release framework, it should do the job on it's own to bump the versions.

**Comment by saimedhi** [comment]
> Why do we need to do version bump manually? Once onboarded to release framework, it should do the job on it's own to bump the versions.

For autosync onboarding,  I am using 2.x branch. From my understanding, initially version should be correct when onboarding to autosync (here 2.17)  and for later releases it will automatically get bumped. 

Let me know if that is not the case. 

cc: @joshpalis

**Review by joshpalis — APPROVED** [review]

**Comment by joshpalis** [comment]
@saimedhi lets wait for a second approval before merging

**Review by ohltyler — APPROVED** [review]
LGTM! Thanks for the changes.

**Comment by owaiskazi19** [comment]
Build is failing
```
 [4/4] Building fresh packages...

ERROR [single_version_dependencies] Multiple version ranges for the same dependency
      were found declared across different package.json files. Please consolidate
error Command failed with exit code 1.
      those to match across all package.json files. Different versions for the
      same dependency is not supported.

      If you have questions about this please reach out to the operations team.

      The conflicting dependencies are:

        js-yaml
          ^3.14.0 => opensearch-dashboards, @osd/apm-config-loader, @osd/config, @osd/optimizer
          ^4.1.0 => dashboards-flow-framework
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ohltyler** [comment]
> Build is failing
> 
> ```
>  [4/4] Building fresh packages...
> 
> ERROR [single_version_dependencies] Multiple version ranges for the same dependency
>       were found declared across different package.json files. Please consolidate
> error Command failed with exit code 1.
>       those to match across all package.json files. Different versions for the
>       same dependency is not supported.
> 
>       If you have questions about this please reach out to the operations team.
> 
>       The conflicting dependencies are:
> 
>         js-yaml
>           ^3.14.0 => opensearch-dashboards, @osd/apm-config-loader, @osd/config, @osd/optimizer
>           ^4.1.0 => dashboards-flow-framework
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

Fixed in #240. Interestingly this wasn't failing before; I checked when there was any js-yaml dependency changes and there hasn't been anything changed recently. Either way, we can remove and consume from core OSD.

**Comment by ohltyler** [comment]
@saimedhi  are we ok to merge, or is there some issues with this version update in 2.x branch with 2.16 release still ongoing?

**Comment by saimedhi** [comment]
> is there some issues with this version update in 2.x branch with 2.16 release still ongoing?

From my understanding, current development is happening for 2.17. So, version should be 2.17 right. And also we did not add 2.x in build repo manifest.

**Comment by ohltyler** [comment]
Sounds good! I will merge.

**Pull request merged**
