### PR TITLE
Show experimental badge on Workflow Details page (new and old)

### PR DESCRIPTION
**Pull request by ohltyler**
### Description

Show experimental badge on Workflow Details page (new and old).

Screenshot (new)
Screenshot 2024-11-18 at 4 38 30 PM

Screenshot (old):
Screenshot 2024-11-18 at 4 39 37 PM

Screenshot (old, popover opened):
Screenshot 2024-11-18 at 4 40 09 PM

### Issues resolved
Makes progress on #461 

### Check List

- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ohltyler** [comment]
Adding for the home Workflows page is WIP.

**Comment by saimedhi** [comment]
@ohltyler, LGTM. But this is slightly different from mockups in #461. 

@kamingleung, Is it okay placing experimental badge beside Last Updated in the header instead of action buttons (Workflow Details or Editor Page -  New Page Header).Please refer screenshots [here](https://github.com/opensearch-project/dashboards-flow-framework/pull/485#issue-2670392173)

**Comment by kamingleung** [comment]
Hi @saimedhi, currently there's a limitation with the header on what can be added next to the action buttons. The temporary workaround is to display the badge next to the "Last updated" timestamp.

**Review by saimedhi — APPROVED** [review]

**Comment by kamingleung** [comment]
@ohltyler @saimedhi How does the badge look in the new look with MDS enabled? Are we able to place the badge on the left of the MDS picker?

**Comment by saimedhi** [comment]
> @ohltyler @saimedhi How does the badge look in the new look with MDS enabled? Are we able to place the badge on the left of the MDS picker like this? image


Hello @kamingleung, We are able to place badge to the left of  MDS picker . 

- For Workflow Details or Editor Page, it can seen here https://github.com/opensearch-project/dashboards-flow-framework/pull/485#issue-2670392173
- For Workflows List Page, please take a look at this PR and let me know if any more changes needed. Thank you. https://github.com/opensearch-project/dashboards-flow-framework/pull/496

**Pull request merged**
