### PR TITLE
Improve input/output transformation configuration

### LINKED ISSUE #491: [META] [FEATURE] Simplify model input configurations
To flexibly handle all input types for a model (static fields, transforms, document fields, templates, etc.), we can have a more structured UI for configuring. The current UI just allows freeform text or a dropdown of available fields, if found. In the end, it is all converted just to text anyways. Below are some of the target mockups highlighting the different input types we should explicitly show:

Screenshot 2024-11-20 at 9 57 17 AM
Screenshot 2024-11-20 at 9 57 26 AM

To accomplish this, we will need to do the following:
- [x] refactor the ML processor components to be more customized #492 
- [x] update the underlying UI config for input transforms - we need to persist some metadata determining the different "types" offered (template vs. document field etc.) #495 
- [x] add abstraction logic to convert constants/templates into the `model_config` field for the ML processor when converting to a final template containing the JSON config body, and leaving document field / transform definitions as values for the input maps #495 
- [x] add & update existing transform modals to support both template configuration, and transform configuration, similar to what exists already #495 / #502
- [x] finalize what will be done for the outputs - do we duplicate some of the logic? The key difference is static values will not be supported - only JSONPath / selecting fields from the model output will be supported. #502

### PR DESCRIPTION
**Pull request by ohltyler**
### Description

This PR merges the `feature/new-transform` feature branch to `main`. The primary changes are:
- adding transform types when configuring inputs
- adding transform types when configuring outputs
- configuring static values & templates in-line for model inputs (no standalone modals needed anymore)
- adding new dedicated modals for configuring some of the different input types, including JSONPath expressions, templates, and multi-JSONPath-expressions (output transforms only). These borrow & refactor a lot of the logic used in the legacy modals, which have now been removed

This changes how the configs for input/output transforms are persisted. Hence, old workflows created with the UI will fail.

### Testing
Tested several use cases and verified the modals work as expected, including the presets, using connector / model configs based off of the [tutorial](https://github.com/opensearch-project/dashboards-flow-framework/blob/main/documentation/tutorial-11-18-2024.md)
- semantic search
- RAG
- hybrid search
- NER
- language detection

### Issues resolved
Closes #491 

### Check List
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ohltyler** [comment]
I will update the [tutorial](https://github.com/opensearch-project/dashboards-flow-framework/blob/main/documentation/tutorial-11-18-2024.md) in a later PR.

**Comment by ohltyler** [comment]
There will also be minor tuning to the preview display values for the different input/output transforms, and some helper text, helper examples of JSONPath, etc. to be added in later PRs. This is all being finalized from UX.

**Comment by saimedhi** [comment]
The feature branch has been tested and is working fine without breaking any existing functionality. I'm ok to merge it into the main branch.

**Review by saimedhi — APPROVED** [review]
LGTM

**Pull request merged**
