### PR TITLE
Add Codecov for test coverage reporting

### PR DESCRIPTION
**Pull request by saimedhi**
### Description

- Add Codecov for test coverage reporting.

### Issues Resolved
Related to #109

### Check List

- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saimedhi** [comment]
Codecov token added is not getting detected by the workflows and throwing errors. Few other repos are experiencing similar issue. Raised bug report in codecov library [here](https://github.com/codecov/feedback/issues/525).

**Comment by saimedhi** [comment]
- @ohltyler, please take a look at this Pr and merge it if possible. 
- From the conversation here, noticed that codecov workflow maynot succeed when Pull Request is raised but codecov update checks will succeed when  PR is merged.

**Comment by ohltyler** [comment]
Few questions:
1. What is the reasoning for the extra params in the workflow step? In AD plugin, we just use the `codecov-action` ([ref](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/.github/workflows/build-and-test-workflow.yml#L48))
2. Suggest we just add this once for one env (linux), instead of adding the step multiple times to prevent duplicate uploads. Or, even better, add as a standalone github workflow file that just handles the coverage so it is decoupled from this 'build and test' workflow. WDYT?

**Comment by saimedhi** [comment]
> Few questions:
> 
> 1. What is the reasoning for the extra params in the workflow step? In AD plugin, we just use the `codecov-action` ([ref](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/.github/workflows/build-and-test-workflow.yml#L48))
> 2. Suggest we just add this once for one env (linux), instead of adding the step multiple times to prevent duplicate uploads. Or, even better, add as a standalone github workflow file that just handles the coverage so it is decoupled from this 'build and test' workflow. WDYT?

1. Added codecov token, which is optional but good to have. 
2. I agree that we should have codecov uploading step running only once. As in the [codecov](https://app.codecov.io/gh/opensearch-project/dashboards-flow-framework), I didn't see any platform specific codecov metrics. Made the change.

**Review by ohltyler — APPROVED** [review]
LGTM thanks for adding!

**Comment by saimedhi** [comment]
- Codecov successfully updated for main, 2.x branches 
- Current code coverage is **48.44%** as seen in below link. 

https://app.codecov.io/gh/opensearch-project/dashboards-flow-framework/tree/main

**Pull request merged**
